application: previousnext/lamp

test: &test
  steps:
    - echo "build.drupal.dir=./app" >> build.properties
    - phing prepare:all
    - phing make
    - mkdir -p app/sites/default/files/tmp
    - mkdir -p app/sites/default/private
    - phing site-install -Ddb.name=drupal_local -Ddb.username=drupal -Ddb.password=drupal -Ddb.host=localhost
    - chown -R www-data:www-data app/sites/default/files
    - chown -R www-data:www-data app/sites/default/private
    - echo "\$base_url = 'https://$DOMAIN';" >> app/sites/default/settings.php

test_pr:
  <<: *test

test_head:
  <<: *test
